### ISSUE TITLE
re-adding distribution fails

### ISSUE THREAD

**Issue by am1337** [ionos-cloud/reprepro#1] opened 2015-11-06 12:39 UTC
Hi,

I am using this reprepro branch to mange multiple distributions. 
It's working great, beside a bug that I found when adding an distribution that has been deleted before.

I did the following steps:
- deleted an distribution from conf/distributions 
- run reprepro --delete clearvanished.
- added same distribution again
- run reprepro export or pull

Then I get this message:

```
$ reprepro pull trusty-test
Calculating packages to pull...
/var/repo//db/packages.db/trusty-test|main|source: BDB0088 DB_SECONDARY_BAD: Secondary index inconsistent with primary
Internal error of the underlying BerkeleyDB database:
Within packages.db subtable trusty-test|main|source at c_get(DB_NEXT): BDB0088 DB_SECONDARY_BAD: Secondary index inconsistent with primary
There have been errors!
```

Using db_dump, I found out, that all entries about "trusty-test" are deleted from packages.db, but not from packages.secondary.db.
I assume that only the rows of the removed database must be deleted from packages.secondary.db and it will work.

Best regards

Achim

**Comment by am1337** [comment] 2015-11-10 08:41
I tried to figure out what goes wrong when deleting a distribution and found that clearvanished does not delete the distribution from secondary database. 
We added the missing function and it seems to work now. But we also had to delete some lines from upgradelist.c as reprepro always exits with an error otherwise.

Can someone confirm this error?

```
$ reprepro pull my-repo
Calculating packages to pull...
Package database is not sorted!!!
reprepro: upgradelist.c:134: save_package_version: Assertion `0' failed.
Abgebrochen (Speicherabzug geschrieben)
```

We are using update and pull mechanism to copy repositories and also provide own packages in some repos.

Is there any other place in code where elements from secondary database must be deleted?

This is our patch:

```
$ git diff main.c database.c upgradelist.c
diff --git a/database.c b/database.c
index c249312..4dfd3b2 100644
--- a/database.c
+++ b/database.c
@@ -2065,11 +2065,16 @@ retvalue database_listpackages(struct strlist *identifiers) {
        return database_listsubtables("packages.db", identifiers);
 }

-/* drop a database */
+/* drop a database (primary) */
 retvalue database_droppackages(const char *identifier) {
        return database_dropsubtable("packages.db", identifier);
 }

+/* drop a database (secondary) */
+retvalue database_droppackages_secondary(const char *identifier) {
+       return database_dropsubtable("packages.secondary.db", identifier);
+}
+
 retvalue database_openfiles(void) {
        retvalue r;
        struct strlist identifiers;
diff --git a/main.c b/main.c
index bed7dd8..5c94cb6 100644
--- a/main.c
+++ b/main.c
@@ -3513,6 +3513,7 @@ ACTION_D(n, n, n, clearvanished) {
                references_remove(identifier);
                /* remove the database */
                database_droppackages(identifier);
+               database_droppackages_secondary(identifier);
        }
        free(inuse);
        strlist_done(&identifiers);
diff --git a/upgradelist.c b/upgradelist.c
index 272b46c..2525487 100644
--- a/upgradelist.c
+++ b/upgradelist.c
@@ -126,14 +126,7 @@ static retvalue save_package_version(struct upgradelist *upgrade, const char *pa
                if (strcmp(packagename, upgrade->last->name) > 0) {
                        upgrade->last->next = package;
                        upgrade->last = package;
-               } else {
-                       /* this should only happen if the underlying
-                        * database-method get changed, so just throwing
-                        * out here */
-                       fprintf(stderr, "Package database is not sorted!!!\n");
-                       assert(false);
-                       exit(EXIT_FAILURE);
-               }
+               } 
        }

        return RET_OK;
```

Best regards

Achim

**Comment by bdrung** [comment] 2016-06-27 15:47
I see this BDB0088 DB_SECONDARY_BAD error in our environment too. Thanks for reporting the issues including the detailed analysis and the fix. It helped me to reproduce the error and verify the fix.

I have included your fix for calling `database_dropsubtable()` on packages.secondary.db and rebased the branch on the 4.17.1 upstream release. `database_droppackages()` is only called in one place and therefore your fix is complete.

I haven't included your change to `upgradelist.c` because I haven't seen this error message and it doesn't look the the correct solution. I am closing this issue since "re-adding distribution fails" is fixed. Feel free to open another issue for it.

**Closed as completed by bdrung** 2016-06-27 15:47 UTC

**Comment by bdrung** [comment] 2016-06-27 16:18
Here is a small Python script to clean-up the packages.secondary.db:

``` python
#!/usr/bin/python3

import bsddb3

packages = bsddb3.btopen('db/packages.db', 'r')
secondary = bsddb3.btopen('db/packages.secondary.db', 'r')

only_in_secondary = set(secondary.keys()) - set(packages.keys())
only_in_secondary = sorted(x.decode() for x in only_in_secondary)

packages.close()
secondary.close()

print("These databases are only available in db/packages.secondary.db:\n" +
      "\n".join(only_in_secondary))

for database in only_in_secondary:
    print("Removing '{}' from db/packages.secondary.db...".format(database))
    db = bsddb3.db.DB()
    db.remove('db/packages.secondary.db', dbname=database)
```
